### ISSUE TITLE
explore other ways to retrieve words for hangman game

### ISSUE THREAD

**Issue by ghost** [salifm/cli-games#82]

**Comment by Seniru** [comment]
Hello yes, I think we should. Right now it only uses a small list of words and could get quite predictable over time.
Running an AI would be quite too much for such a simple task in my opinion. Using an API should be a good idea.

This game has several files of different locales. So it'd be great to use an API that supports any locale.

There is a file `/usr/share/dict/words` in my linux system which has a huge list of words. Would be better if we can go for an approach like that to avoid any uncertainity that could come from external APIs.
